### ISSUE TITLE
warning: `+' after local variable or literal is interpreted as binary operator

### ISSUE THREAD

**Issue by perlun** [colbygk/log4r#52]
I'm getting errors like this on JRuby 9.1.2.0:

> /Volumes/extra/git/mio/mio.salesstatistics/workers/gems/jruby/2.3.0/gems/log4r-1.1.10/lib/log4r/outputter/outputter.rb:54: warning: '+' after local variable or literal is interpreted as binary operator
> /Volumes/extra/git/mio/mio.salesstatistics/workers/gems/jruby/2.3.0/gems/log4r-1.1.10/lib/log4r/outputter>/outputter.rb:54: warning: even though it seems like unary operator
> /Volumes/extra/git/mio/mio.salesstatistics/workers/gems/jruby/2.3.0/gems/log4r-1.1.10/lib/log4r/formatter/formatter.rb:72: warning: '+' after local variable or literal is interpreted as binary operator
> /Volumes/extra/git/mio/mio.salesstatistics/workers/gems/jruby/2.3.0/gems/log4r-1.1.10/lib/log4r/formatter/formatter.rb:72: warning: even though it seems like unary operator

**Comment by ThePix** [comment]
I see similar when using Paperclip gem, but with an ampersand. It can be readily reproduced in irb with this:
`
1 &~ 1
`
It did not happen with JRuby 9.0.4.

**Comment by perlun** [comment]
It's probably because this has changed in Ruby 2.3 vs Ruby 2.2. (JRuby 9.1.2 implements the Ruby 2.3 semantics)

**Comment by cworsley4** [comment]
@perlun how did you address that? This repo doesn't seem particularly active with PRs...

**Comment by perlun** [comment]
Haven't addressed it yet. I think someone should do a fork of this repo and try to get things sorted out a bit; it seems abandoned upstream unfortunately. 😢

**Comment by olleolleolle** [comment]
Here's a patch:
https://github.com/incubus/log4r/pull/1

**Comment by amalrik** [comment]
Same issue here, using Jruby 9.1.7
tried to use last version of log4r(1.1.11) but getting this error:

```
Could not find gem 'log4r (= 1.1.11) java', which is required by gem
```

**Comment by perlun** [comment]
`log4r` is unfortunately rather abandoned it seems. 😢 We migrated over to another logging library instead.

**Comment by sshaw** [comment]
>  We migrated over to another logging library instead...

@perlun care to share which one?

**Comment by perlun** [comment]
> care to share which one?

Sure, https://github.com/chef/mixlib-log

It's very minimal, but has kind of everything we need. We also added usage of [the Rainbow gem](https://github.com/sickill/rainbow) to add some coloring of the output.

**Comment by perlun** [comment]
Closing for lack of feedback, have moved away from log4r ourselves. So long and thanks for the fish, it was nice.
